{% set version = "0.5.29" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rio
  version: {{ version|replace("-", "_") }}

source:
  fn: rio_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rio/rio_{{ version }}.tar.gz
  sha256: 9fa63187e1814053e6ed2a164665b4924e08c3453adccb78f7211d403dcc5412

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-curl >=0.6
    - r-data.table >=1.9.8
    - r-foreign
    - r-haven >=1.1.0
    - r-openxlsx
    - r-readxl >=0.1.1
    - r-tibble
  run:
    - r-base
    - r-curl >=0.6
    - r-data.table >=1.9.8
    - r-foreign
    - r-haven >=1.1.0
    - r-openxlsx
    - r-readxl >=0.1.1
    - r-tibble

test:
  commands:
    - $R -e "library('rio')"           # [not win]
    - "\"%R%\" -e \"library('rio')\""  # [win]

about:
  home: https://github.com/leeper/rio
  license: GPL-2.0
  summary: "Streamlined data import and export by making assumptions that the user is probably willing to make: 'import()' and 'export()' determine the data structure from the file extension, reasonable defaults are used for data import and export (e.g., 'stringsAsFactors=FALSE'), web-based import is natively supported (including\
    \ from SSL/HTTPS), compressed files can be read directly without explicit decompression, and fast import packages are used where appropriate. An additional convenience function, 'convert()', provides a simple method for converting between file types."
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
