{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rio/rio_{{ version }}.tar.gz
  sha256: 4baf892fd43faaef6886a1074d9433d55481ab681e0b93f077d8610d5e49b3d4

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-arrow >=0.17.0
    - r-curl >=0.6
    - r-data.table >=1.11.2
    - r-foreign
    - r-haven >=1.1.2
    - r-lifecycle
    - r-readxl >=0.1.1
    - r-stringi
    - r-tibble
    - r-writexl
  run:
    - r-base
    - r-r.utils
    - r-arrow >=0.17.0
    - r-curl >=0.6
    - r-data.table >=1.11.2
    - r-foreign
    - r-haven >=1.1.2
    - r-lifecycle
    - r-readxl >=0.1.1
    - r-stringi
    - r-tibble
    - r-writexl

test:
  commands:
    - $R -e "library('rio')"           # [not win]
    - "\"%R%\" -e \"library('rio')\""  # [win]

about:
  home: https://github.com/leeper/rio
  license: GPL-2.0-only
  summary: "Streamlined data import and export by making assumptions that the user is probably willing to make: 'import()' and 'export()' determine the data structure from the file extension, reasonable defaults are used for data import and export (e.g., 'stringsAsFactors=FALSE'), web-based import is natively supported (including
    from SSL/HTTPS), compressed files can be read directly without explicit decompression, and fast import packages are used where appropriate. An additional convenience function, 'convert()', provides a simple method for converting between file types."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
