travis:
  secure:
    BINSTAR_TOKEN: pZ8GvULbTG+1NubK2VRgdSrpVb5vrPpKXgBFPST1e4SWJ1M+zyr4pKtyytb2odjsDc8fgLio7VPwgpsc3+uZP9c8UNBkKDC0gdFxVjDvQ/trZvjul401rCPJwPaq2LKu8NXwzRUA/blgpNkdrqZc6SH7hFeocmPtFJfHN+PmLiAciZuxHPqhiZ0oVGAK6N2GPtF15n+8NdF2VRHogsIHKU8kBrnivOXrFYtOvKwbUCBeIGPTfFciGCcrx2ucS6UpmpD8Euv3t9WfPKTGTx6WxShGZqNF71L9sfwVEmQueCIXTXiII8CBTRKfriO5xfJ1gktOkxyFnZxgU1AFGGIoZBV7Gm4XvGWylCMPQ0IlyX/Fnre0xfxkT+PKjMqTISKp7JMkW9uXAJfIre65ItYWdWmomEdRAnpt3gR5BLRub4H19zgL6PpSFi3liQJ4w4ALZAYDG9DsLGeWwHwtAf8Bs6i6Q8yPNfa2gI9VkbofIKjhxcrMKVbYDGRbHCsq8y5Mk+cuRQP5Pne8YhXtxEobmsWbelys4IxsXIaN1ypms8bhXfBHejefNFcg1xw+zvj4siWdY04lui5w7qw0CBVKxOGRZUvLZENqIqefguQBQgNADdsnuseQ/Y/hPABpvzIskQdbSgeEP4fP9WfthbedmCmrSjMYiCeOsBbSFvjLYlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
