travis:
  secure:
    BINSTAR_TOKEN: Jco6iKli6ebxYDDKq8CnjjUNBIXhjvv+7K6H/ZNPMJ/t7jkdBDzyns66vxmKuMLNcK5uzP3AFJ+x8Uh6RL7e0qTN8EFL5g4BYWnXsewips6oVrWMlPdzae0Gbrufj4AJRYxh0aFhUWtmhO8YnmL6wRqyiFf/QiMm35XajzuJfiNrI0ywbhT82goIhCTgrQTyD/0P+WDXDUBJyNFi0mCSH7r/T/f775nacZK1xKmjgSvQGPX2YHEsefNvG0NoaUcamWV6ryNVmBIxCXHRcyWp1ivUEiKDwnQvv346qtqnsAIbfb6bLWXenQT4AZ76grgcStE4PRKlNAq4KgOgF5s5Udn8jgm4Otz15fpkXW/C3KnsdHcfDaGsVuyCE3Tylg+nSx0mGOg+Bw/KHCYGBHwsNg4bI3O0vTKOEFF56qNmzhUK8ZWKX5HTsTuUxpb9YB+Lhcw6Fq0lAYc74y/rZWzdIwczQE3piXx/zuiktxQOYfE4dCBHhv6hGusnM+KXLNgnkeRG9QZN9C50CSRv5I0rIeaec20h4LdcU3Q5cwHO5xf0ZpA7cb0SeSZELRc2ne07tzlfz3VsWhkwU2YkGrulW8pMUo87glqdNwGX4zWtliBjm6G1zqaycBsno9nOWzjwpqwx27u3YFHxsioKhUybxXTmvVyXbottsbyG+QsUB78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
