travis:
  secure:
    BINSTAR_TOKEN: SVdYgEeIpAVVEMewWdbsGZb3TCTnyvXtOAVdA9G0YoLS/jdbtpUQlVeFZjTFivsuSUE3dUNrSxDjteSHi6Smx4Kqp6i0/ou4ZyNKmiv/4nVUMj4gZo4ZZFxdFML4/cnesVtXAVLV8B5ICP1oJ8m8F/vC82SmSYWwVvnSzzQHjIs2LJHRb04tuBIHzF/VT1EM8Qsco6NbT0YBiXtDV+dmhgFs65XOL8ZgqOXEf3K3sc7UbuqZJUbH+rbLUx/8MrqZBgolwMgjgbWZuxhtWAqXT64t9b6v2MUgE91gyvD3H/2BuiknXZ2lBVBPXUgsqvbjQkCnb80o4/wb9JHFN2cD7SKta4wQLEPNBq+yTdd5Z4UhRZvx0ldEQC5d9wumssu1tchxG8ewOmv0vlUO0dVHBmvnXiZfngCBRpSqIPgIqHycDfWcnPswzKFawlyXr710QEhlkyCVKtqaHbrBmw0iGd0mUhPY/Gd1g1DYiJ9FO1jke/7+eg6mETpUz+nrkRkyVHYjVDFYOjQEI4H7hv02grs9FxwpUshTzKgDSGyFY+3bHa7Ei/YfjZ5ltwNZNODQb9BQzDXtChyiEhSBJ7hthWa+kXumvHbELAjE9ruwZwGyFYuTPVIFifcjEBu6VUZWUE2e7/2KgfVIJbl1GEMQZ94mtsGMwYFDLd5phaL81Jw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
